### PR TITLE
daemon: fix version update checks

### LINKED ISSUE #716: inertia incorrectly reports upgrade is available
```
❯ inertia rocket2 status

Inertia daemon on remote "rocket2" (...) is online
...
Inertia daemon v0.7.0

🚀  Inertia version v0.7.0 is now available!
Go to https://github.com/ubclaunchpad/inertia/releases/tag/v0.7.0 for more details.
Run 'inertia rocket2 upgrade --help' for tips on upgrading.
```

### PR DESCRIPTION
**Pull request by cheukyin699**
:tickets: **Ticket(s)**: Closes #716 

---

## :construction_worker: Changes

Check that the current version of inertiad is actually not the latest version before saying that a new version is available.

## :flashlight: Testing Instructions

Not sure about that one. Will need help.

### CODE REVIEW

**Review by bobheadxi — APPROVED** [review]
Awesome, thanks! Do you think you could try and include a case for this in the tests? https://sourcegraph.com/github.com/ubclaunchpad/inertia/-/blob/daemon/inertiad/daemon/status_test.go#L64 (not necessary I suppose but would be nice :) )

**Comment by cheukyin699** [comment]
> Awesome, thanks! Do you think you could try and include a case for this in the tests? [sourcegraph.com/github.com/ubclaunchpad/inertia/-/blob/daemon/inertiad/daemon/status_test.go#L64](https://sourcegraph.com/github.com/ubclaunchpad/inertia/-/blob/daemon/inertiad/daemon/status_test.go#L64) (not necessary I suppose but would be nice :) )

I'll try

**Comment by cheukyin699** [comment]
@bobheadxi Need some help. Not sure why the Deployment status doesn't update even after putting it into another variable. Is it copying it?

```go
func TestStatusHandlerNotUpToDate(t *testing.T) {
	status := api.DeploymentStatus{
		Branch:               "wow",
		CommitHash:           "abcde",
		CommitMessage:        "",
		Containers:           []string{},
		BuildContainerActive: false,
	}

	var s = &Server{
		deployment: &mocks.FakeDeployer{
			GetStatusStub: func(*docker.Client) (api.DeploymentStatus, error) {
				return status, nil
			},
		},
		version: "v1.0.0",
	}

	// Assemble request
	req, err := http.NewRequest("GET", "/status", nil)
	assert.NoError(t, err)

	// Record responses
	recorder := httptest.NewRecorder()
	handler := http.HandlerFunc(s.statusHandler)

	handler.ServeHTTP(recorder, req)
	assert.Equal(t, recorder.Code, http.StatusOK)

	// Check status
	assert.Equal(t, status.InertiaVersion, s.version)			// sanity checking, which doesn't work
	assert.NotNil(t, status.NewVersionAvailable)
	assert.NotEqual(t, status.NewVersionAvailable, s.version)
}
```

**Comment by bobheadxi** [comment]
@cheukyin699 the `GetStatusStub` mocks the `deployment`'s status function, you will need to include the version in `status` :)

```go
	status := api.DeploymentStatus{
		Branch:               "wow",
		CommitHash:           "abcde",
		CommitMessage:        "",
		Containers:           []string{},
		BuildContainerActive: false,
		InertiaVersion:       "v1.0.0",
	}
```

https://sourcegraph.com/github.com/ubclaunchpad/inertia/-/blob/api/response.go#L92

**Pull request merged**
